variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  PACKAGE_VERSION: "0.1.1"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/y_rb/${PACKAGE_VERSION}"

stages:
  - build
  - upload
  - release

build:
  stage: build
  image: ruby:${RUBY_VERSION}
  script:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - source /builds/gitlab-org/incubation-engineering/real-time-editing/yrb/.cargo/env
    - gem install bundler
    - bundle install
    - bundle exec rake thermite:tarball
  artifacts:
    paths:
      - "y_rb-*.tar.gz"
  parallel:
    matrix:
      - RUBY_VERSION: ["2.6", "2.7", "3.0", "3.1"]
        TAGS: ["linux"]

upload:
  stage: upload
  image: curlimages/curl:latest
#  rules:
#    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file y_rb-${PACKAGE_VERSION}-ruby26-linux-x86_64.tar.gz "${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby26-linux-x86_64.tar.gz"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file y_rb-${PACKAGE_VERSION}-ruby27-linux-x86_64.tar.gz "${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby27-linux-x86_64.tar.gz"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file y_rb-${PACKAGE_VERSION}-ruby30-linux-x86_64.tar.gz "${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby30-linux-x86_64.tar.gz"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file y_rb-${PACKAGE_VERSION}-ruby31-linux-x86_64.tar.gz "${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby31-linux-x86_64.tar.gz"
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
#  rules:
#    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release ${PACKAGE_VERSION}" --tag-name "v${PACKAGE_VERSION}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby26-linux-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby26-linux-x86_64.tar.gz\"}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby27-linux-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby27-linux-x86_64.tar.gz\"}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby30-linux-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby30-linux-x86_64.tar.gz\"}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby31-linux-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby31-linux-x86_64.tar.gz\"}" \
